### ISSUE TITLE
[Windows] ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by robinhood2014** [deep5050/radio-active#101]
**Describe the bug**
On Windows, when I run `radio`, I get the following error output:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\donni\AppData\Local\Programs\Python\Python312\Scripts\radio.exe\__main__.py", line 4, in <module>
  File "C:\Users\donni\AppData\Local\Programs\Python\Python312\Lib\site-packages\radioactive\__main__.py", line 11, in <module>
    from radioactive.handler import Handler
  File "C:\Users\donni\AppData\Local\Programs\Python\Python312\Lib\site-packages\radioactive\handler.py", line 10, in <module>
    from pyradios import RadioBrowser
  File "C:\Users\donni\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyradios\__init__.py", line 3, in <module>
    from pyradios.radios import RadioBrowser
  File "C:\Users\donni\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyradios\radios.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**To Reproduce**
1. Open Windows PowerShell or PowerShell 7.
2. Type `radio` with any or no parameters.
3. See error

**Expected behavior**
E.g. when running `radio` with no parameters, I expected a welcome message as described by Derek Taylor a.k.a. "DistroTube" at 5:25 of his video covering this app. Below this, I expected the program to print a message in red letters saying, "No station to play. please [sic] search for a station first!"

**Screenshots**
I've enclosed two screenshots illustrating the different scenarios. The first screenshot is the result of the native Windows version; I obtained the second from running the same command in a Windows Subsystem for Linux (WSL) environment.
![Screenshot 2023-11-08 212557](https://github.com/deep5050/radio-active/assets/6971466/62d37a8f-595e-4733-ad52-4fe07427ac49)
![Screenshot 2023-11-08 212415](https://github.com/deep5050/radio-active/assets/6971466/69312dcb-498d-48b2-bacf-1c5842c40468)

**Desktop**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 119

**Additional context**
It's possible that this might not be a bug at all, but instead a result of me being a bonehead and forgetting to install a dependency for the native Windows version. Whatever the case may be, _please_ let me know what's up.

**Comment by WyntrHeart** [comment]
Same issue on Android 9 using Termux

**Comment by WyntrHeart** [comment]
Fixed this by installing "setuptools" which provides the module "pkg_resources". Since pip doesn't install this package automatically it should be listed as a dependency for radio-active

**Comment by robinhood2014** [comment]
@WyntrHeart Confirmed fixed on Windows. I'm not sure why Python pulls in the "pkg_resources" module by default on desktop Linux but not on any other platform.

**Comment by deep5050** [comment]
Thank you for the bug working..
