### ISSUE TITLE
Improvement to "--list" flag

### ISSUE THREAD

**Issue by robinhood2014** [deep5050/radio-active#104]
Right now, `radio --list` shows the user's list of favorite stations and then drops them right back to the shell. Perhaps we could improve the `--list` flag so it asks the user if (s)he wants to play a station from that list? We could attach numbers to the favorites list, and the user could just input the number of the station (s)he wants (or, say, 0 to go back to the shell as before).

On a related note, we could also improve the question `Type the result ID to play:` so it will actually accept 0 as a valid input to go back to the shell. This already does work, but the program also prints error messages at the end before dropping to the shell. Perhaps the user legitimately changed his/her mind and didn't want to play anything? In that case, if (s)he enters 0, don't print the unnecessary error messages.

**Comment by deep5050** [comment]
invoking `radio`  without any options allows you to select a station from your favorite menu already. I don't think we should unnecessarily play from the favorite list table.
