### ISSUE TITLE
connection errors when supplying -U station-UUID

### ISSUE THREAD

**Issue by auntchilada** [deep5050/radio-active#55]
**Describe the bug**

i have successfully connected to stations via UUID, but i've encountered reproducible connection errors via UUID for two stations:

> .$ radio -U a256200d-2ec4-11e9-8f31-52543be04c81
> ...
>
>       i     | Station found: KALX 90.7FM Berkeley
> │                               KALX 90.7FM Berkeley
>
> Enter a command to perform an action:     [!!!]   | Could not connect to the station
>     [!!!]   | Invalid data found when processing input
>       i     | Exiting now

**To Reproduce**

in the following shell session, i have snipped the info box and some superfluous grafix

# ----------- / shell session

.$ radio --version

      i     | RADIO-ACTIVE : version 2.6.0

.$ ### set terminal geometry wide to eliminate chopped UUID ( i don't like to resize windows ;-)

.$ COLUMNS=600 radio -S kalx

[!]    | 2 stations found by the name, select one and run with UUID instead

┃ Station              ┃                 UUID                 ┃ Country ┃                   Tags                    ┃

│ kalx                 │ fd08c2d1-bca3-49b6-938e-24223869e278 │   US    │             university radio              │
│ KALX 90.7FM Berkeley │ a256200d-2ec4-11e9-8f31-52543be04c81 │   US    │ aac,berkeley,uc berkeley,university radio │

i     | If the table does not fit into your screen,
i     | try to maximize the window , decrease the font by a bit and retry

.$ radio -U fd08c2d1-bca3-49b6-938e-24223869e278

i     | Station found: kalx
────────────────────────────────────────╮
│                                       kalx

Enter a command to perform an action:  [!!!]   | Could not connect to the station
[!!!]   | Invalid data found when processing input
  i     | Exiting now

.$ radio -U a256200d-2ec4-11e9-8f31-52543be04c81

i     | Station found: KALX 90.7FM Berkeley
────────────────────────────────────────╮
│                               KALX 90.7FM Berkeley

Enter a command to perform an action:  [!!!]   | Could not connect to the station
[!!!]   | Invalid data found when processing input
  i     | Exiting now

**Expected behavior**

connect and play the station

**Desktop (please complete the following information):**

OS: macOS Ventura 13.6 22G120 x86_64
Host: MacBook Air (Retina, 13-inch, 2020)
Kernel: 22.6.0
Packages: 837 (brew), 279 (brew-cask), 7 (port)
Shell: bash 5.2.15
Display (Color LCD): 2880x1800 @ 61Hz (as 1440x900)
DE: Aqua
WM: Quartz Compositor
Terminal: Apple Terminal 447
Terminal Font: LigaSFMonoNerdFont-Regular (15pt)
CPU: Intel(R) Core(TM) i3-1000NG4 (4) @ 1.1 GHz
GPU: Intel Iris Plus Graphics (1.50 GiB) [Integrated]
Memory: 4.36 GiB / 8.00 GiB (54%)
Disk (/): 143.48 GiB / 233.47 GiB (61%) - apfs [Read-only]
Locale: en_US.UTF-8

**Additional context**

--

Please let me know if there are any questions or issues.

regards,

auntchilada

**Comment by deep5050** [comment]
Hi, thanks for the issue.

I have checked the error. It's not an issue from the app. The station is somehow streaming with wrong/unsupported configuration that ffmpeg can't handle. 

I'll still investigate it.
