### ISSUE TITLE
radio exits but player plays perfectly in the background!!

### ISSUE THREAD

**Issue by deep5050** [deep5050/radio-active#66]
![image](https://github.com/deep5050/radio-active/assets/27947066/0db365ae-3e29-494c-bd2e-0add6707eb7a)

     ...    | Update not available
      i     | You can search for a station on internet using the --search option
     ...    | Error: 'stationuuid'
     ...    | player: url => https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio008/hlspbaudio008_Auto.m3u8
     ...    | FFplay: /usr/bin/ffplay
     ...    | player: ffplay => PID 3641 initiated
     ...    | Saving the current station: {'name': 'AIR FM Rainbow Mumbai ', 'uuid_or_url': 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio008/hlspbaudio008_Auto.m3u8'}
     ...    | Dumping station information
╭─────────────────────────────────────── 📻 ────────────────────────────────────────╮
│                               AIR FM Rainbow Mumbai                               │
╰───────────────────────────────────────────────────────────────────────────────────╯
     ...    | codec falling back to: 'NoneType' object is not subscriptable
[NULL @ 0x55f5b6831e00] Invalid HLS ID3 audio timestamp 69406134857
    [!!!]   | Could not connect to the station
     ...    | [NULL @ 0x7f97fc62b880] Invalid HLS ID3 audio timestamp 69406134857
     ...    | Error: list index out of range
     ...    | Radio is not currently playing
     ...    | You pressed Ctrl+C!
     ...    | Stopping the radio
      i     | Exiting now
Documents/github/radio-active$

**Comment by dimyself** [comment]
i'm having a similiar issue

mine exits without an error and also without playing anything

i'm on arch and have radioaCtive installed in a venv. i do have ffplay

i search and find a station, "do you want to play?" Y

it then just exits without any error and without any other output. Nothing plays though

i tried it with strace, and it just exits

> exit_group(0)                           = ?
> +++ exited with 0 +++

**Comment by deep5050** [comment]
Would you please run it with "--log debug " and share the output?

**Comment by dimyself** [comment]
Hmm i updated my system ... and now, its working... i swear it wasn't
working earlier (although i only tried a few stations)

Though, if i try the linux unplugged station by searching for: linux

it still exits without any message

 bin/radio --search linux --log debug
╭─────────────────────────────────── RADIOACTIVE
───────────────────────────────────╮
│
        │
│         📻 Play any radios around the globe right from this Terminal ⚡!
       │
│         😄 Author: Dipankar Pal
        │
│         ❓ Type '--help' for more details on available commands
        │
│         🐛 Visit: https://github.com/deep5050/radio-active to submit
issues       │
│         ⭐ Show some love by starring the project on GitHub ❤
        │
│         💵 You can donate me at https://deep5050.github.io/payme/
        │
│         ❌ Press Ctrl+C to quit
        │
│
        │
╰───────────────────────────────────────────────────────────────────────────────────╯
     ...    | Update not available
     ...    | Searching API for: linux
      i     | Station found: Linux Unplugged
     ...    | {
     ...    |    "changeuuid": "f5ddf56c-2564-44f6-bd88-8aa8d243db5b",
     ...    |    "stationuuid": "cda8a118-629f-4edd-8afe-897a61519297",
     ...    |    "serveruuid": null,
     ...    |    "name": "Linux Unplugged",
     ...    |    "url": "
https://chtbl.com/track/392D9/aphid.fireside.fm/d/1437767933/f31a453c-fa15-491f-8618-3f71f1d565e5/e62102e1-655c-45ab-8a7f-d973435419e7.mp3
",
     ...    |    "url_resolved": "
https://media.fireside.fm/file/fireside-audio/podcasts/audio/f/f31a453c-fa15-491f-8618-3f71f1d565e5/episodes/e/e62102e1-655c-45ab-8a7f-d973435419e7/e62102e1-655c-45ab-8a7f-d973435419e7.mp3
",
     ...    |    "homepage": "https://linuxunplugged.com/",
     ...    |    "favicon": "
https://assets.fireside.fm/file/fireside-images/podcasts/images/f/f31a453c-fa15-491f-8618-3f71f1d565e5/touch_icon_iphone.png?v=3
",
     ...    |    "tags": "",
     ...    |    "country": "The United States Of America",
     ...    |    "countrycode": "US",
     ...    |    "iso_3166_2": null,
     ...    |    "state": "",
     ...    |    "language": "",
     ...    |    "languagecodes": "",
     ...    |    "votes": 121,
     ...    |    "lastchangetime": "2022-03-28 08:39:10",
     ...    |    "lastchangetime_iso8601": "2022-03-28T08:39:10Z",
     ...    |    "codec": "MP3",
     ...    |    "bitrate": 0,
     ...    |    "hls": 0,
     ...    |    "lastcheckok": 1,
     ...    |    "lastchecktime": "2023-10-16 05:15:33",
     ...    |    "lastchecktime_iso8601": "2023-10-16T05:15:33Z",
     ...    |    "lastcheckoktime": "2023-10-16 05:15:33",
     ...    |    "lastcheckoktime_iso8601": "2023-10-16T05:15:33Z",
     ...    |    "lastlocalchecktime": "2023-10-16 05:15:33",
     ...    |    "lastlocalchecktime_iso8601": "2023-10-16T05:15:33Z",
     ...    |    "clicktimestamp": "2023-10-15 22:08:42",
     ...    |    "clicktimestamp_iso8601": "2023-10-15T22:08:42Z",
     ...    |    "clickcount": 23,
     ...    |    "clicktrend": 8,
     ...    |    "ssl_error": 0,
     ...    |    "geo_lat": null,
     ...    |    "geo_long": null,
     ...    |    "has_extended_info": false
     ...    | }
     ...    | Exactly one result found
Want to play this station? Y/N: Y
     ...    | Quitting

and i checked the mP3 url, and it plays in a browser, so i'm not sure
whats going on

but earlier the couple music stations i tried exited the same way as above.

maybe good to have more verbose output about whats wrong or why its exiting?

thank you!

**Comment by javierisassi** [comment]
I got the same issue:
To reproduce:
radio --search "100.3 big"
╭─────────────────────────────────── RADIOACTIVE ───────────────────────────────────╮
│                                                                                   │
│         📻 Play any radios around the globe right from this Terminal ⚡!          │
│         😄 Author: Dipankar Pal                                                   │
│         ❓ Type '--help' for more details on available commands                   │
│         🐛 Visit: https://github.com/deep5050/radio-active to submit issues       │
│         ⭐ Show some love by starring the project on GitHub ❤                     │
│         💵 You can donate me at https://deep5050.github.io/payme/                 │
│         ❌ Press Ctrl+C to quit                                                   │
│                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────╯
      i     | Station found: 100.3 big
Want to play this station? Y/N:  Y
Enter a command to perform an action: ?
    [!!!]   | Could not connect to the station
    [!!!]   | n42a-e2.revma.ihrhls.com:-1 != ample.revma.ihrhls.com:-1

ffmpeg remains happily running in the background. To kill:
pgrep ffmpeg | xargs kill -9
Temporary patch should capture the pid of ffmpeg and cleanup before calling it quits.

**Comment by mindfulnessbergamo** [comment]
Radio playing in the background after quitting via ctrl+c  happened to me too. Seems like a random behaviour. I am on Windows 10 Pro.
