### ISSUE TITLE
Optionally show streaming url of the station currently played

### ISSUE THREAD

**Issue by ghmon** [deep5050/radio-active#76]
Optionally show streaming url of the station currently played.

**Comment by deep5050** [comment]
we can do that from the runtime commands. otherwise the UI will get ugly

**Comment by deep5050** [comment]
will work on this

**Comment by ghmon** [comment]
Thank you very much. I forgot to say - radio-active is in the current very mighty and really nice! Thanks. The "streaming url" request is "low prio" for me.

**Comment by esturniolo** [comment]
+1

**Comment by deep5050** [comment]
will be available on 2.8.1

**Comment by deep5050** [comment]
implemented. type "i' on runtime
