### ISSUE TITLE
q does not quit radio-active

### ISSUE THREAD

**Issue by mindfulnessbergamo** [deep5050/radio-active#98]
Windows 10 Pro, Cmder, radio-active 2.9.0
Search for radios in France => radio -C fr
Get the list of french radios
Type the ID I want to listen to
Radio starts streaming
Enter q to stop streaming and quit radio-active
Message "No background radios are running!"
New radio-active prompt while radio keeps streaming

**Comment by deep5050** [comment]
That should not be the case, maybe you are trying to quit before the `ffplay`  process starts playing the station.

let me investigate

**Comment by mindfulnessbergamo** [comment]
No, I try to quit AFTER `ffplay` process has started playing the station

**Comment by mindfulnessbergamo** [comment]
FYI, it happened also in version 2.8.0

**Comment by deep5050** [comment]
working on it. found the issue

**Comment by mindfulnessbergamo** [comment]
v 2.9.1
q is working fine now
